return {
    'mason-org/mason-lspconfig.nvim',
    dependencies = {
        'mason-org/mason.nvim',
    },
    opts = {
        ensure_installed = {
            'bashls',
            'biome',
            'clangd',
            'css_variables',
            'cssls',
            'cssmodules_ls',
            'docker_compose_language_service',
            'dockerls',
            'html',
            'jsonls',
            'lua_ls',
            'marksman',
            'nginx_language_server',
            'postgres_lsp',
            'ruff',
            'rust_analyzer',
            'ty',
            'vtsls',
            'yamlls',
            'zls',
        },
    },
}
