return {
	'nvim-treesitter/nvim-treesitter',
	dependencies = {
		'nvim-treesitter/nvim-treesitter-textobjects',
	},
	build = ':TSUpdate',
	main = 'nvim-treesitter.configs',
	event = { 'BufReadPost', 'BufNewFile' },
	init = function(plugin)
		require('lazy.core.loader').add_to_rtp(plugin)
		require('nvim-treesitter.query_predicates')
	end,
	keys = {
		{ '<C-space>', desc = 'Increment Selection' },
		{ '<bs>', desc = 'Decrement Selection', mode = 'x' },
	},
	opts = {
		ensure_installed = {
			'bash',
			'css',
			'csv',
			'diff',
			'dockerfile',
			'git_config',
			'git_rebase',
			'gitattributes',
			'gitcommit',
			'gitignore',
			'graphql',
			'html',
			'http',
			'javascript',
			'jsdoc',
			'json',
			'jsonc',
			'lua',
			'luadoc',
			'luap',
			'markdown',
			'markdown_inline',
			'nginx',
			'pem',
			'python',
			'query',
			'regex',
			'scss',
			'ssh_config',
			'sql',
			'toml',
			'tsx',
			'typescript',
			'vim',
			'vimdoc',
			'xml',
			'yaml',
		},
		highlight = {
			enable = true,
		},
		indent = { enable = true },
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = '<C-space>',
				node_incremental = '<C-space>',
				scope_incremental = false,
				node_decremental = '<bs>',
			},
		},
		textobjects = {
			move = {
				enable = true,
				goto_next_start = { [']f'] = '@function.outer', [']c'] = '@class.outer', [']a'] = '@parameter.inner' },
				goto_next_end = { [']F'] = '@function.outer', [']C'] = '@class.outer', [']A'] = '@parameter.inner' },
				goto_previous_start = {
					['[f'] = '@function.outer',
					['[c'] = '@class.outer',
					['[a'] = '@parameter.inner',
				},
				goto_previous_end = { ['[F'] = '@function.outer', ['[C'] = '@class.outer', ['[A'] = '@parameter.inner' },
			},
		},
	},
}
