return {
	'nvim-treesitter/nvim-treesitter',
	build = ':TSUpdate',
	main = 'nvim-treesitter.configs',
	event = { 'BufReadPost', 'BufNewFile' },
	opts = {
		ensure_installed = {
			'bash',
			'css',
			'csv',
			'diff',
			'dockerfile',
			'git_config',
			'git_rebase',
			'gitattributes',
			'gitcommit',
			'gitignore',
			'graphql',
			'html',
			'http',
			'javascript',
			'json',
			'jsonc',
			'lua',
			'markdown',
			'markdown_inline',
			'nginx',
			'pem',
			'python',
			'query',
			'regex',
			'scss',
			'ssh_config',
			'sql',
			'toml',
			'tsx',
			'typescript',
			'vim',
			'vimdoc',
			'yaml',
		},
		sync_install = false,
		auto_install = true,
		highlight = {
			enable = true,
			additional_vim_regex_highlighting = false,
		},
		indent = { enable = true },
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = '<C-space>',
				node_incremental = '<C-space>',
				scope_incremental = false,
				node_decremental = '<bs>',
			},
		},
	},
}
